-- Phase 1D: playbook revisions and published immutability.
-- Additive only: new enum, new table, new nullable column, FKs/indexes, a backfill (revision 1 = each existing
-- playbook as it is now, PUBLISHED) and PostgreSQL triggers. No existing row or column is changed or removed,
-- except setting playbooks.published_revision_id for the backfilled revision.

-- ---------------------------------------------------------------------------------------------------------------
-- Schema (generated by `prisma migrate diff` from schema.prisma; verified to contain no DROP)

-- CreateEnum
CREATE TYPE "playbook_revision_status" AS ENUM ('DRAFT', 'IN_REVIEW', 'APPROVED', 'PUBLISHED', 'SUPERSEDED', 'REJECTED');

-- AlterTable
ALTER TABLE "playbooks" ADD COLUMN     "published_revision_id" TEXT;

-- CreateTable
CREATE TABLE "playbook_revisions" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "playbook_id" TEXT NOT NULL,
    "revision_number" INTEGER NOT NULL,
    "version" TEXT NOT NULL,
    "status" "playbook_revision_status" NOT NULL DEFAULT 'DRAFT',
    "content" JSONB NOT NULL,
    "proposal_reason" TEXT,
    "created_by" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reviewed_by" TEXT,
    "reviewed_at" TIMESTAMP(3),
    "approved_by" TEXT,
    "approved_at" TIMESTAMP(3),
    "published_by" TEXT,
    "published_at" TIMESTAMP(3),
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "playbook_revisions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "playbook_revisions_tenant_id_idx" ON "playbook_revisions"("tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "playbook_revisions_playbook_id_revision_number_key" ON "playbook_revisions"("playbook_id", "revision_number");

-- CreateIndex
CREATE UNIQUE INDEX "playbook_revisions_playbook_id_version_key" ON "playbook_revisions"("playbook_id", "version");

-- CreateIndex
CREATE UNIQUE INDEX "playbooks_published_revision_id_key" ON "playbooks"("published_revision_id");

-- AddForeignKey
ALTER TABLE "playbooks" ADD CONSTRAINT "playbooks_published_revision_id_fkey" FOREIGN KEY ("published_revision_id") REFERENCES "playbook_revisions"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "playbook_revisions" ADD CONSTRAINT "playbook_revisions_playbook_id_fkey" FOREIGN KEY ("playbook_id") REFERENCES "playbooks"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "playbook_revisions" ADD CONSTRAINT "playbook_revisions_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------------------------------------------
-- Backfill: every existing playbook gets revision 1 = its current content, PUBLISHED, and points to it.
-- Runs before the triggers below exist, so the publication invariant is only checked on the finished state.
INSERT INTO "playbook_revisions" (
  "id", "tenant_id", "playbook_id", "revision_number", "version", "status", "content", "proposal_reason",
  "created_by", "created_at", "published_by", "published_at", "updated_at"
)
SELECT
  gen_random_uuid()::text,
  p."tenant_id",
  p."id",
  1,
  COALESCE(p."version", '1.0'),
  'PUBLISHED',
  jsonb_build_object(
    'code', p."code",
    'name', p."name",
    'description', p."description",
    'triggerConditions', p."trigger_conditions",
    'n8nWorkflowId', p."n8n_workflow_id",
    'playbookStatus', p."status",
    'version', p."version",
    'steps', COALESCE((
      SELECT jsonb_agg(jsonb_build_object('stepOrder', s."step_order", 'title', s."title", 'description', s."description") ORDER BY s."step_order")
      FROM "playbook_steps" s WHERE s."playbook_id" = p."id"
    ), '[]'::jsonb)
  ),
  'Phase 1D backfill: revision 1 is the playbook as it was before revisions existed',
  'system:phase1d-backfill',
  CURRENT_TIMESTAMP,
  'system:phase1d-backfill',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
FROM "playbooks" p;

UPDATE "playbooks" p
SET "published_revision_id" = r."id"
FROM "playbook_revisions" r
WHERE r."playbook_id" = p."id" AND r."revision_number" = 1;

-- Abort the whole migration if the backfill is incomplete.
DO $$
DECLARE
  n_playbooks bigint; n_revisions bigint; n_missing bigint; n_steps bigint; n_content_steps bigint;
BEGIN
  SELECT count(*) INTO n_playbooks FROM "playbooks";
  SELECT count(*) INTO n_revisions FROM "playbook_revisions" WHERE "revision_number" = 1 AND "status" = 'PUBLISHED';
  SELECT count(*) INTO n_missing FROM "playbooks" WHERE "published_revision_id" IS NULL;
  SELECT count(*) INTO n_steps FROM "playbook_steps";
  SELECT COALESCE(sum(jsonb_array_length("content"->'steps')), 0) INTO n_content_steps FROM "playbook_revisions";
  IF n_revisions <> n_playbooks OR n_missing <> 0 OR n_content_steps <> n_steps THEN
    RAISE EXCEPTION 'Phase 1D backfill incomplete: playbooks=%, published revisions=%, missing pointers=%, steps=%, steps in content=%',
      n_playbooks, n_revisions, n_missing, n_steps, n_content_steps;
  END IF;
END $$;

-- ---------------------------------------------------------------------------------------------------------------
-- Immutability: from APPROVED on, content, version and identity are frozen, and the revision cannot go back to an
-- editable state (which would otherwise allow "flip to DRAFT, then edit").
CREATE FUNCTION "playbook_revision_guard_update"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD."status" IN ('APPROVED', 'PUBLISHED', 'SUPERSEDED') THEN
    IF NEW."content" IS DISTINCT FROM OLD."content" THEN
      RAISE EXCEPTION 'PLAYBOOK_REVISION_IMMUTABLE: content of % revision % cannot be changed', OLD."status", OLD."id"
        USING ERRCODE = 'check_violation';
    END IF;
    IF NEW."version" IS DISTINCT FROM OLD."version" OR NEW."playbook_id" IS DISTINCT FROM OLD."playbook_id"
       OR NEW."revision_number" IS DISTINCT FROM OLD."revision_number" OR NEW."tenant_id" IS DISTINCT FROM OLD."tenant_id"
       OR NEW."created_by" IS DISTINCT FROM OLD."created_by" OR NEW."created_at" IS DISTINCT FROM OLD."created_at" THEN
      RAISE EXCEPTION 'PLAYBOOK_REVISION_IMMUTABLE: identity/version of % revision % cannot be changed', OLD."status", OLD."id"
        USING ERRCODE = 'check_violation';
    END IF;
    IF NEW."status" IN ('DRAFT', 'IN_REVIEW', 'REJECTED') THEN
      RAISE EXCEPTION 'PLAYBOOK_REVISION_IMMUTABLE: % revision % cannot return to %', OLD."status", OLD."id", NEW."status"
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER "playbook_revision_guard_update"
  BEFORE UPDATE ON "playbook_revisions"
  FOR EACH ROW EXECUTE FUNCTION "playbook_revision_guard_update"();

-- Historical revisions are never deleted: PUBLISHED (required), and APPROVED / SUPERSEDED (rollback targets and the
-- content historical recommendations refer to by code + version).
CREATE FUNCTION "playbook_revision_guard_delete"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD."status" IN ('APPROVED', 'PUBLISHED', 'SUPERSEDED') THEN
    RAISE EXCEPTION 'PLAYBOOK_REVISION_IMMUTABLE: % revision % cannot be deleted', OLD."status", OLD."id"
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN OLD;
END $$;

CREATE TRIGGER "playbook_revision_guard_delete"
  BEFORE DELETE ON "playbook_revisions"
  FOR EACH ROW EXECUTE FUNCTION "playbook_revision_guard_delete"();

-- Tenant isolation: a revision always belongs to its playbook's tenant.
CREATE FUNCTION "playbook_revision_guard_tenant"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW."tenant_id" IS DISTINCT FROM (SELECT p."tenant_id" FROM "playbooks" p WHERE p."id" = NEW."playbook_id") THEN
    RAISE EXCEPTION 'PLAYBOOK_REVISION_TENANT_MISMATCH: revision % tenant differs from its playbook', NEW."id"
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER "playbook_revision_guard_tenant"
  BEFORE INSERT OR UPDATE OF "tenant_id", "playbook_id" ON "playbook_revisions"
  FOR EACH ROW EXECUTE FUNCTION "playbook_revision_guard_tenant"();

-- Publication invariant, checked at COMMIT (deferred) so publish / rollback can swap revisions inside one transaction:
-- at most one PUBLISHED revision per playbook, and playbooks.published_revision_id points to exactly that revision
-- (or is NULL when the playbook has none).
CREATE FUNCTION "playbook_check_publication"(p_playbook_id text) RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  n_published int; published_id text; pointer text;
BEGIN
  SELECT count(*), max("id") INTO n_published, published_id
  FROM "playbook_revisions" WHERE "playbook_id" = p_playbook_id AND "status" = 'PUBLISHED';
  SELECT "published_revision_id" INTO pointer FROM "playbooks" WHERE "id" = p_playbook_id;
  IF NOT FOUND THEN RETURN; END IF;
  IF n_published > 1 THEN
    RAISE EXCEPTION 'PLAYBOOK_PUBLICATION_INVALID: playbook % has % PUBLISHED revisions', p_playbook_id, n_published
      USING ERRCODE = 'check_violation';
  END IF;
  IF pointer IS DISTINCT FROM published_id THEN
    RAISE EXCEPTION 'PLAYBOOK_PUBLICATION_INVALID: playbook % points to % but its PUBLISHED revision is %', p_playbook_id, pointer, published_id
      USING ERRCODE = 'check_violation';
  END IF;
END $$;

CREATE FUNCTION "playbook_publication_from_playbook"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  PERFORM "playbook_check_publication"(NEW."id");
  RETURN NULL;
END $$;

CREATE FUNCTION "playbook_publication_from_revision"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  PERFORM "playbook_check_publication"(NEW."playbook_id");
  IF TG_OP = 'UPDATE' AND OLD."playbook_id" IS DISTINCT FROM NEW."playbook_id" THEN
    PERFORM "playbook_check_publication"(OLD."playbook_id");
  END IF;
  RETURN NULL;
END $$;

CREATE CONSTRAINT TRIGGER "playbook_publication_from_playbook"
  AFTER INSERT OR UPDATE OF "published_revision_id" ON "playbooks"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION "playbook_publication_from_playbook"();

CREATE CONSTRAINT TRIGGER "playbook_publication_from_revision"
  AFTER INSERT OR UPDATE OF "status", "playbook_id" ON "playbook_revisions"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION "playbook_publication_from_revision"();
