<script setup lang="ts">
// Create a Playbook or edit its open Draft (Knowledge -> Playbooks; SOC, IR_TEAM and admin; the backend enforces the role).
// Both save a DRAFT only: nothing is used until SOC / IR_TEAM press Publish (no approval step). A published version is
// never edited here: "Create New Version" makes a draft copy first. Only fields the existing Playbook domain has.
// Human-controlled: nothing here is generated by the AI.
import { computed, reactive, ref, watch } from 'vue'
import { ArrowDown, ArrowUp, Loader2, Trash2 } from 'lucide-vue-next'
import Modal from '@/components/common/Modal.vue'
import { knowledgeApi, playbookVersionsApi } from '@/api/vigix'
import { ApiError } from '@/api/http'
import { useI18n, type MsgKey } from '@/i18n'
import { workflowError } from '@/utils/workflow'
import { draftFromPlaybook, emptyPlaybookDraft, hasErrors, playbookPayload, validatePlaybookDraft, type DraftErrors, type PlaybookDraft } from '@/utils/playbookForm'
import { draftSource } from '@/utils/playbookLifecycle'

/** playbookId + revisionId = edit that DRAFT revision; no playbookId = create (a new DRAFT playbook). */
const props = defineProps<{ open: boolean; playbookId: string | null; revisionId?: string | null; existingCodes: string[] }>()
const emit = defineEmits<{ close: []; saved: [code: string, created: boolean] }>()
const { t } = useI18n()

const creating = computed(() => !props.playbookId)
const draft = reactive<PlaybookDraft>(emptyPlaybookDraft())
const errors = ref<DraftErrors>({})
const touched = ref(false)
const loading = ref(false)
const saving = ref(false)
const serverError = ref('')
const draftVersion = ref('')

watch(
  () => [props.open, props.playbookId, props.revisionId] as const,
  async ([open, id, revisionId]) => {
    if (!open) return
    Object.assign(draft, emptyPlaybookDraft())
    errors.value = {}
    touched.value = false
    serverError.value = ''
    draftVersion.value = ''
    if (!id) return
    loading.value = true
    try {
      // Edit the draft's own content (not the live playbook row).
      const revision = (await playbookVersionsApi.list(id)).items.find((r) => r.id === revisionId && r.status === 'DRAFT')
      if (!revision) throw Object.assign(new Error('draft not found'), { code: 'INVALID_REVISION_TRANSITION' })
      draftVersion.value = revision.version
      Object.assign(draft, draftFromPlaybook(draftSource(revision)))
    } catch (e) {
      serverError.value = workflowError(e)
    } finally {
      loading.value = false
    }
  },
  { immediate: true },
)
// Re-validate as the user types once they tried to save (messages follow the language too).
watch(draft, () => { if (touched.value) errors.value = validatePlaybookDraft(draft, creating.value, props.existingCodes) }, { deep: true })

const addStep = () => draft.steps.push({ title: '', description: '' })
const removeStep = (i: number) => { draft.steps.splice(i, 1); if (!draft.steps.length) addStep() }
function move(i: number, delta: number) {
  const j = i + delta
  if (j < 0 || j >= draft.steps.length) return
  const [s] = draft.steps.splice(i, 1)
  draft.steps.splice(j, 0, s)
}

function serverMessage(e: unknown): string {
  if (e instanceof ApiError) {
    if (e.code === 'DUPLICATE_CODE') return t('pbf.err.codeDuplicate')
    if (e.code === 'FORBIDDEN' || (e.status === 403 && e.code !== 'SERVICE_PRINCIPAL_FORBIDDEN')) return t('pbf.err.forbidden')
    if (e.code === 'VALIDATION_ERROR') return t('pbf.err.server')
  }
  return workflowError(e)
}

async function save() {
  if (saving.value || loading.value) return
  touched.value = true
  errors.value = validatePlaybookDraft(draft, creating.value, props.existingCodes)
  if (hasErrors(errors.value)) return
  saving.value = true
  serverError.value = ''
  try {
    const body = playbookPayload(draft, creating.value)
    if (creating.value) {
      const saved = await knowledgeApi.create('playbooks', body)
      emit('saved', String(saved.code ?? draft.code), true)
    } else {
      await playbookVersionsApi.updateDraft(props.playbookId!, props.revisionId!, body)
      emit('saved', draft.code, false)
    }
  } catch (e) {
    serverError.value = serverMessage(e)
  } finally {
    saving.value = false
  }
}
const fieldError = (k: 'code' | 'name' | 'incidentType' | 'steps') => (errors.value[k] ? t(errors.value[k] as MsgKey) : '')
const inputClass = (bad: boolean) => ['mt-1 w-full rounded-lg border px-3 py-1.5 text-sm focus:outline-none', bad ? 'border-rose-400 focus:border-rose-500' : 'border-slate-300 focus:border-accent-500']
</script>

<template>
  <Modal :open="open" :title="creating ? t('pbf.createTitle') : t('pbl.editDraftTitle', { code: draft.code, v: draftVersion })" size="lg" @close="!saving && emit('close')">
    <p v-if="loading" class="flex items-center gap-2 text-sm text-slate-500" role="status"><Loader2 class="size-4 animate-spin" /> {{ t('pbf.loading') }}</p>
    <form v-else class="space-y-4 text-sm" novalidate @submit.prevent="save">
      <fieldset class="space-y-4" :disabled="saving">
        <div class="grid gap-4 sm:grid-cols-2">
          <label v-if="creating" class="block font-medium text-slate-700">{{ t('pbf.code') }} *
            <input v-model="draft.code" :class="inputClass(!!errors.code)" class="font-mono uppercase" autocomplete="off" :aria-invalid="!!errors.code" />
            <span class="mt-0.5 block text-[11px] font-normal text-slate-400">{{ t('pbf.codeHint') }}</span>
            <span v-if="errors.code" class="mt-0.5 block text-xs font-normal text-rose-700" role="alert">{{ fieldError('code') }}</span>
          </label>
          <label class="block font-medium text-slate-700" :class="creating ? '' : 'sm:col-span-2'">{{ t('pbf.name') }} *
            <input v-model="draft.name" :class="inputClass(!!errors.name)" maxlength="200" :aria-invalid="!!errors.name" />
            <span v-if="errors.name" class="mt-0.5 block text-xs font-normal text-rose-700" role="alert">{{ fieldError('name') }}</span>
          </label>
        </div>
        <label class="block font-medium text-slate-700">{{ t('pbf.description') }}
          <textarea v-model="draft.description" rows="2" maxlength="2000" :class="inputClass(false)" />
        </label>
        <div class="grid gap-4 sm:grid-cols-2">
          <label class="block font-medium text-slate-700">{{ t('pbf.incidentType') }}
            <input v-model="draft.incidentType" :class="inputClass(!!errors.incidentType)" class="font-mono uppercase" autocomplete="off" :aria-invalid="!!errors.incidentType" />
            <span class="mt-0.5 block text-[11px] font-normal text-slate-400">{{ t('pbf.incidentTypeHint') }}</span>
            <span v-if="errors.incidentType" class="mt-0.5 block text-xs font-normal text-rose-700" role="alert">{{ fieldError('incidentType') }}</span>
          </label>
          <label class="block font-medium text-slate-700">{{ t('pbl.statusAfterPublish') }}
            <select v-model="draft.status" :class="inputClass(false)">
              <option value="ACTIVE">{{ t('pbf.st.ACTIVE') }}</option>
              <option value="DEPRECATED">{{ t('pbf.st.DEPRECATED') }}</option>
            </select>
          </label>
        </div>

        <div>
          <p class="font-medium text-slate-700">{{ t('pbf.steps') }} *</p>
          <p v-if="errors.steps" class="mt-0.5 text-xs text-rose-700" role="alert">{{ fieldError('steps') }}</p>
          <ol class="mt-2 space-y-2">
            <li v-for="(s, i) in draft.steps" :key="i" class="rounded-lg border border-slate-200 p-2.5">
              <div class="flex items-start gap-2">
                <span class="mt-1.5 w-14 shrink-0 text-xs font-semibold text-slate-500">{{ t('pbf.stepTitle', { n: i + 1 }) }}</span>
                <div class="min-w-0 flex-1 space-y-1.5">
                  <input v-model="s.title" :placeholder="t('pbf.stepTitlePlaceholder')" :aria-label="t('pbf.stepTitle', { n: i + 1 })" :class="inputClass(!!errors.stepTitles?.includes(i))" class="!mt-0" maxlength="300" />
                  <textarea v-model="s.description" rows="1" :placeholder="t('pbf.stepDescPlaceholder')" :class="inputClass(false)" class="!mt-0" maxlength="2000" />
                  <span v-if="errors.stepTitles?.includes(i)" class="block text-xs text-rose-700" role="alert">{{ t('pbf.err.stepTitle') }}</span>
                </div>
                <div class="flex shrink-0 flex-col gap-0.5">
                  <button type="button" class="rounded p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-700 disabled:opacity-30" :disabled="i === 0" :aria-label="t('pbf.moveUp', { n: i + 1 })" @click="move(i, -1)"><ArrowUp class="size-3.5" /></button>
                  <button type="button" class="rounded p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-700 disabled:opacity-30" :disabled="i === draft.steps.length - 1" :aria-label="t('pbf.moveDown', { n: i + 1 })" @click="move(i, 1)"><ArrowDown class="size-3.5" /></button>
                  <button type="button" class="rounded p-1 text-slate-400 hover:bg-rose-50 hover:text-rose-600" :aria-label="t('pbf.removeStep', { n: i + 1 })" @click="removeStep(i)"><Trash2 class="size-3.5" /></button>
                </div>
              </div>
            </li>
          </ol>
          <button type="button" class="mt-2 text-xs font-semibold text-accent-700 hover:underline" @click="addStep">{{ t('pbf.addStep') }}</button>
        </div>
      </fieldset>

      <p class="rounded-lg bg-slate-50 px-3 py-2 text-xs text-slate-600">{{ t('pbl.draftNote') }}</p>
      <p v-if="serverError" class="rounded-lg bg-rose-50 px-3 py-2 text-sm text-rose-700" role="alert">{{ serverError }}</p>
      <div class="flex justify-end gap-2">
        <button type="button" class="btn-secondary" :disabled="saving" @click="emit('close')">{{ t('c.cancel') }}</button>
        <button type="submit" class="btn-primary inline-flex items-center gap-2" :disabled="saving || loading"><Loader2 v-if="saving" class="size-4 animate-spin" />{{ saving ? t('pbf.saving') : t('pbf.save') }}</button>
      </div>
    </form>
  </Modal>
</template>
