/** Attack-specific response guidance after a verified re-hunt detects spread. Actions remain evidence gated. */
export const SPREAD_RESPONSES = [
  { incidentType: "SSH_BRUTE_FORCE", playbookCode: "PB-SSH-BRUTEFORCE", actions: ["ACT-BLOCK-SOURCE-IP", "ACT-RATE-LIMIT-SOURCE", "ACT-REVOKE-SESSION", "ACT-DISABLE-ACCOUNT", "ACT-RESET-CREDENTIAL"], guidance: "Stop the recorded attacking source across the newly affected SSH services. Rate-limit repeated attempts. Revoke sessions or disable/reset an account only when evidence confirms successful unauthorized access. Do not isolate a host merely because authentication failed." },
  { incidentType: "MALWARE", playbookCode: "PB-MALWARE", actions: ["ACT-ISOLATE-ENDPOINT", "ACT-KILL-PROCESS", "ACT-QUARANTINE-FILE", "ACT-BLOCK-HASH", "ACT-BLOCK-DOMAIN", "ACT-BLOCK-URL", "ACT-BLOCK-DESTINATION-IP", "ACT-BLOCK-SOURCE-IP"], guidance: "Contain each newly infected endpoint supported by the re-hunt. Stop the evidenced malicious process and quarantine the identified payload. Block the recorded delivery or C2 indicators to prevent further infection; do not assume every matching host is infected without checking the event." },
  { incidentType: "SQL_INJECTION", playbookCode: "PB-SQL-INJECTION", actions: ["ACT-BLOCK-SOURCE-IP", "ACT-RATE-LIMIT-SOURCE", "ACT-REVOKE-SESSION", "ACT-RESET-CREDENTIAL"], guidance: "Block or rate-limit the evidenced injection source at the affected web services. Revoke the abused session or reset a credential only if the re-hunt supports identity compromise. Verify the control protects the newly affected services; an injection attempt alone does not establish a database breach." },
  { incidentType: "ACCOUNT_COMPROMISE", playbookCode: "PB-ACCOUNT-COMPROMISE", actions: ["ACT-REVOKE-SESSION", "ACT-DISABLE-ACCOUNT", "ACT-RESET-CREDENTIAL", "ACT-BLOCK-SOURCE-IP", "ACT-ISOLATE-ENDPOINT"], guidance: "Invalidate the recorded compromised identity's active sessions and contain further access by disabling or resetting that identity as the evidence permits. Block the recorded external access source. Isolate newly affected endpoints only when malicious use of those endpoints is evidenced." },
  { incidentType: "POWERSHELL", playbookCode: "PB-POWERSHELL", actions: ["ACT-ISOLATE-ENDPOINT", "ACT-KILL-PROCESS", "ACT-QUARANTINE-FILE", "ACT-BLOCK-HASH", "ACT-BLOCK-DOMAIN", "ACT-BLOCK-URL", "ACT-BLOCK-SOURCE-IP", "ACT-DISABLE-ACCOUNT"], guidance: "Contain each newly affected endpoint with evidenced malicious PowerShell activity. Stop the recorded malicious process, quarantine an identified script/payload and block its recorded delivery indicators. Disable an identity only if abuse is established. A PowerShell process name alone is not proof of malicious execution." },
  { incidentType: "PHISHING", playbookCode: "PB-PHISHING", actions: ["ACT-QUARANTINE-EMAIL", "ACT-BLOCK-SENDER", "ACT-BLOCK-URL", "ACT-BLOCK-DOMAIN", "ACT-BLOCK-HASH", "ACT-REVOKE-SESSION", "ACT-RESET-CREDENTIAL", "ACT-DISABLE-ACCOUNT", "ACT-ISOLATE-ENDPOINT"], guidance: "Remove evidenced malicious messages from newly affected recipients and stop the recorded sender, URL or domain. Revoke sessions/reset credentials only for evidenced interaction or credential theft. Isolate an endpoint only after confirming attachment execution or endpoint compromise; message delivery alone does not justify isolation." },
  { incidentType: "COMMAND_AND_CONTROL", playbookCode: "PB-C2", actions: ["ACT-BLOCK-DESTINATION-IP", "ACT-BLOCK-DOMAIN", "ACT-BLOCK-URL", "ACT-ISOLATE-ENDPOINT", "ACT-BLOCK-HASH"], guidance: "Cut the recorded outbound C2 destinations and contain newly beaconing endpoints supported by the re-hunt. Block a payload hash only when it is recorded. Use the destination IOC, not the reporting agent's IP, and verify communication stops on all newly affected endpoints." },
  { incidentType: "DATA_EXFILTRATION", playbookCode: "PB-DATA-EXFIL", actions: ["ACT-BLOCK-DESTINATION-IP", "ACT-BLOCK-DOMAIN", "ACT-BLOCK-URL", "ACT-ISOLATE-ENDPOINT", "ACT-REVOKE-SESSION", "ACT-DISABLE-ACCOUNT"], guidance: "Stop transfers to the recorded exfiltration destination and contain newly affected source endpoints. Revoke sessions or disable an identity only when it is evidenced as participating in the transfer. Verify the outbound transfer stops; do not claim how much data was lost without evidence." },
  { incidentType: "PRIVILEGE_ESCALATION", playbookCode: "PB-PRIV-ESC", actions: ["ACT-REMOVE-PRIVILEGE", "ACT-REVOKE-SESSION", "ACT-DISABLE-ACCOUNT", "ACT-KILL-PROCESS", "ACT-ISOLATE-ENDPOINT"], guidance: "Remove the recorded unauthorized privilege, revoke the abusing identity's sessions and stop the evidenced elevated process. Contain newly affected endpoints when successful escalation or persistence is supported. Do not assert escalation succeeded solely from an exploit attempt." },
  { incidentType: "SUSPICIOUS_PROCESS_EXECUTION", playbookCode: "PB-SUSPICIOUS-PROCESS", actions: ["ACT-KILL-PROCESS", "ACT-QUARANTINE-FILE", "ACT-BLOCK-HASH", "ACT-ISOLATE-ENDPOINT"], guidance: "Stop the evidenced suspicious process on each newly affected endpoint, quarantine the identified payload and block the recorded hash. Isolate an endpoint when compromise is established. Confirm process identity before termination and do not invent a process ID or file path." },
] as const;

export const spreadPolicyCode = (incidentType: string) => `SPREAD-${incidentType.replace(/_/g, "-")}`;
